---
title: "Homework 8"
author: "Gwen Ellis"
date: "2024-03-20"
output: html_document
---


```{r, include=FALSE}
library(tidyverse)
data("iris")
```


## Question 1
```{r}
str(iris)
# 150 observations and 5 variables

```


## Question 2
```{r}
iris1 <- iris %>% 
  filter(Species == c("virginica", "versicolor"), Sepal.Length > 6.0, Sepal.Width > 2.5)

str(iris1)
# 28 observations and 5 variables
```

## Question 3
```{r}
iris2 <- iris1 %>%
  select(Species, Sepal.Length, Sepal.Width)

str(iris2)
# 28 observations and 3 variables
```

## Question 4
```{r}
iris3 <- iris2 %>% 
  arrange(by=desc(Sepal.Length))

print(head(iris3), 6)

```

## Question 5
```{r}
iris4 <- iris3 %>% 
  mutate(Sepal.Area = Sepal.Length*Sepal.Width)

str(iris4)
# 28 observations and 4 variables
```

## Question 6
```{r}
iris5 <- c(avg_sepal.length = mean(iris4$Sepal.Length), avg_sepal.width = mean(iris4$Sepal.Width), avg_sepal.area = mean(iris4$Sepal.Area))

print(iris5)

```

## Question 7
```{r}
iris6 <- iris4 %>% 
  group_by(Species) %>%
  summarize(avg_sepal.length = mean(Sepal.Length), avg_sepal.width = mean(Sepal.Width), number=n())
  
print(iris6)
```

## Question 8
```{r}
irisFinal <- iris %>% 
  filter(Species == c("virginica", "versicolor"), Sepal.Length > 6.0, Sepal.Width > 2.5) %>% 
  select(Species, Sepal.Length, Sepal.Width) %>% 
  group_by(Species) %>%
  summarize(avg_sepal.length = mean(Sepal.Length), avg_sepal.width = mean(Sepal.Width), number=n())

```

## Question 9
```{r}
iris <- iris %>% 
  mutate(ID = 1:length(iris$Sepal.Length))

iris_long <- pivot_longer(iris, cols=Sepal.Length:Petal.Width, names_to="Meaure", values_to="Value")

```

