---
title: "Homework 4"
author: "Gwen Ellis"
date: "2024-02-07"
output: html_document
---

## Question 1 
```{r}
x <- 1.1
a <- 2.2
b <- 3.3

# a.
z <- x^(a^b)
print(z)

# b.
z <- (x^a)^b
print(z)

# c.
z <- 3*x^3 + 2*x^2 + 1
print(z)

```

## Question 2
```{r}
# a.
c(seq(1,8),seq(7,1))

# b.
rep(x=seq(1,5),times=seq(1,5))

# c. 
rep(x=seq(5,1),times=seq(1,5))

```

## Question 3
```{r}
cartesian <- runif(2)

polar <- c((((cartesian[1])^2 + (cartesian[2])^2)^.5),(atan(cartesian[2]/cartesian[1])))
print(polar)

```

## Question 4
```{r}
queue <- c("sheep","fox","owl","ant")

# a. serpent arrives and gets in line
queue <- c(queue,"serpent")
print(queue)

# b. sheep enters the ark
queue <- queue[-1]
print(queue)

# c.donkey arrives and cuts to the front
queue <- c("donkey",queue)
print(queue)

# d. serpent leaves
queue <- queue[-length(queue)]
print(queue)

# e. owl leaves
queue <- queue[c(1,2,4)]
print(queue)

# f. aphid arrives and goes in front of the ant
queue <- c(queue[1:2], "aphid", queue[3])
print(queue)

# g. where is the aphid in line?
print(length(queue[-1]))

```

## Question 5
```{r}
# not divisible by 2, 3, 7

num <- seq(1,100)
print(which(num%%2 !=0 & num%%3 !=0 & num%%7 !=0))

```

